import p2_img from "./breakfast.webp";
import p3_img from "./lunch1.avif";
import p4_img from "./dinner.jpg";



let all_product = [
  {
    id: 1,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 15.0,
    old_price: 20.0,
  },
  {
    id: 2,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 3,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    id: 4,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 100.0,
    old_price: 150.0,
  },
  {
    id: 5,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 6,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 7,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 8,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 9,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 10,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 11,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 12,
    name: "Healthy & Hygine Lunch",
    category: "lunch",
    image: p3_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 13,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 14,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 15,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 16,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 17,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 18,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 19,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 20,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 21,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 22,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 23,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 24,
    name: "Healthy & Hygine Breakfast",
    category: "breakfast",
    image: p2_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 25,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 26,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 27,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 28,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 29,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 30,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 31,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 32,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 33,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 34,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 35,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    id: 36,
    name: "Healthy & Hygine Dinner",
    category: "dinner",
    image: p4_img,
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
